version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password
      MYSQL_DATABASE: task_db
      MYSQL_USER: task_user
      MYSQL_PASSWORD: task_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  

  app:
    build: .
    container_name: springboot-app
    restart: always
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_NAME: task_db
      DB_USER: task_user
      DB_PASSWORD: task_pass
      TWILIO_SID: AC8cec0ed814b2f652f0050416e00a5a00
      TWILIO_AUTH_TOKEN: 48be69dcf45a8186dd97723a4ba6f54b
      TWILIO_WHATSAPP_NUMBER: whatsapp:+14155238886
    ports:
      - "8080:8080"

volumes:
  mysql_data:
    driver: local  
