version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    secrets:
      - db_password
      - db_name
      - db_user

  app:
    build: .
    container_name: springboot-app
    restart: always
    depends_on:
      - mysql-db
    environment:
      DB_HOST_FILE: /run/secrets/db_host
      DB_NAME_FILE: /run/secrets/db_name
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
      TWILIO_SID_FILE: /run/secrets/twilio_sid
      TWILIO_AUTH_TOKEN_FILE: /run/secrets/twilio_auth_token
      TWILIO_WHATSAPP_NUMBER_FILE: /run/secrets/twilio_whatsapp_number
    ports:
      - "8080:8080"
    secrets:
      - db_host
      - db_name
      - db_user
      - db_password
      - twilio_sid
      - twilio_auth_token
      - twilio_whatsapp_number

secrets:
  db_host:
    file: ./secrets/db_host
  db_name:
    file: ./secrets/db_name
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password
  twilio_sid:
    file: ./secrets/twilio_sid
  twilio_auth_token:
    file: ./secrets/twilio_auth_token
  twilio_whatsapp_number:
    file: ./secrets/twilio_whatsapp_number

volumes:
  mysql_data:
